### ISSUE TITLE
Information for you.

### ISSUE THREAD

**Issue by ArghKevin** [stevefolta/spft#1]
Hello. I appreciate your effort. I'd like to share some information with you.

1. mlterm isn't the only other terminal emulator with support for proportional typefaces. 9term provides support for proportional typefaces, and [a program for columnating generic terminal output](https://9fans.github.io/plan9port/man/man1/mc.html). See https://ftrv.se/21 for a showcase. Below is a screenshot of how I generally use it.
![9tl](https://github.com/stevefolta/spft/assets/50538286/18aa026b-1484-4fb2-84c2-f97c51d92db6)
In your defense, this program [and its cousins ](https://9fans.github.io/plan9port/man/man1/acme.html) require a special conversion process from scalable to bitmap typefaces, and have no support for subpixel anti-aliasing. spft and mlterm share that advantage.
2. Here are the best comparisons I know to your favorite, Helvetica Neue Light. DejaVu Sans Light, FreeSans, and SST Light. The stuff made by paid professionals usually looks best. DejaVu Sans and FreeSans started out as Bitstream Vera Sans and URW Nimbus Sans respectively, each made by paid professionals. They have the benefits afforded by vast character sets. If you've got a budget, I can recommend [SST Light](https://www.fonts.com/font/monotype/sst/paneuropean-light). It was produced [foremost to be an extension of Frutiger to be used in PlayStation user interfaces](https://fontsinuse.com/uses/58376/playstation-4-user-interface), Sony's equivalent to to [Microsoft's Segoe](https://microsoft.com/).
![cmp](https://github.com/stevefolta/spft/assets/50538286/6074b528-2e5c-48c8-8d85-ed0bfb69c4a1)
See what interesting typefaces you may find.

**Comment by ArghKevin** [comment]
Some last-minute notes:
If you'd like to be better at finding typefaces, see https://typographica.org/.
You may find a professional opinion on free typefaces at[ Matthew Butterick's site on practical typography](https://practicaltypography.com/free-fonts.html). He neglects to mention [Bigelow and Holmes's Go](https://go.dev/blog/go-fonts), a proportional typeface for programmers by seasoned professionals. If you've got time on your hands, try [The LaTeX Font Catalogue](https://tug.org/FontCatalogue/sansseriffonts.html). All free typefaces, some of good quality.

**Comment by stevefolta** [comment]
Thanks for the info.  I thought I'd tried FreeSans before but apparently not.  It's definitely close, just a tad heavy.

I took a quick look at how Plan9 does that columnation.  A quick glance at the 9term source doesn't seem to indicate any support for "elastic tabs", actually I'm not sure it handles tabs itself at all.  The mc source seems to indicate that it can measure the text width in the current window's font, and it just emits as many tabs as are needed to get to the next column.
